<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    use HasFactory;

    protected $guarded = [];

    public static function semua_akses()
    {
        return [
            ['id' => 'akses_master', 'name' => ucwords(str_replace('_', ' ', 'akses_master'))],
            ['id' => 'akses_daftar_jabatan', 'name' => ucwords(str_replace('_', ' ', 'akses_daftar_jabatan'))],
            ['id' => 'akses_tambah_jabatan', 'name' => ucwords(str_replace('_', ' ', 'akses_tambah_jabatan'))],
            ['id' => 'akses_edit_jabatan', 'name' => ucwords(str_replace('_', ' ', 'akses_edit_jabatan'))],
            ['id' => 'akses_hapus_jabatan', 'name' => ucwords(str_replace('_', ' ', 'akses_hapus_jabatan'))],
            ['id' => 'akses_daftar_user', 'name' => ucwords(str_replace('_', ' ', 'akses_daftar_user'))],
            ['id' => 'akses_tambah_user', 'name' => ucwords(str_replace('_', ' ', 'akses_tambah_user'))],
            ['id' => 'akses_edit_user', 'name' => ucwords(str_replace('_', ' ', 'akses_edit_user'))],
            ['id' => 'akses_hapus_user', 'name' => ucwords(str_replace('_', ' ', 'akses_hapus_user'))],
            ['id' => 'akses_daftar_stasiun', 'name' => ucwords(str_replace('_', ' ', 'akses_daftar_stasiun'))],
            ['id' => 'akses_tambah_stasiun', 'name' => ucwords(str_replace('_', ' ', 'akses_tambah_stasiun'))],
            ['id' => 'akses_edit_stasiun', 'name' => ucwords(str_replace('_', ' ', 'akses_edit_stasiun'))],
            ['id' => 'akses_hapus_stasiun', 'name' => ucwords(str_replace('_', ' ', 'akses_hapus_stasiun'))],
            ['id' => 'akses_daftar_satuan', 'name' => ucwords(str_replace('_', ' ', 'akses_daftar_satuan'))],
            ['id' => 'akses_tambah_satuan', 'name' => ucwords(str_replace('_', ' ', 'akses_tambah_satuan'))],
            ['id' => 'akses_edit_satuan', 'name' => ucwords(str_replace('_', ' ', 'akses_edit_satuan'))],
            ['id' => 'akses_hapus_satuan', 'name' => ucwords(str_replace('_', ' ', 'akses_hapus_satuan'))],
            ['id' => 'akses_daftar_parameter', 'name' => ucwords(str_replace('_', ' ', 'akses_daftar_parameter'))],
            ['id' => 'akses_tambah_parameter', 'name' => ucwords(str_replace('_', ' ', 'akses_tambah_parameter'))],
            ['id' => 'akses_edit_parameter', 'name' => ucwords(str_replace('_', ' ', 'akses_edit_parameter'))],
            ['id' => 'akses_hapus_parameter', 'name' => ucwords(str_replace('_', ' ', 'akses_hapus_parameter'))],
            ['id' => 'akses_daftar_material', 'name' => ucwords(str_replace('_', ' ', 'akses_daftar_material'))],
            ['id' => 'akses_tambah_material', 'name' => ucwords(str_replace('_', ' ', 'akses_tambah_material'))],
            ['id' => 'akses_edit_material', 'name' => ucwords(str_replace('_', ' ', 'akses_edit_material'))],
            ['id' => 'akses_hapus_material', 'name' => ucwords(str_replace('_', ' ', 'akses_hapus_material'))],
            ['id' => 'akses_daftar_titik_flow', 'name' => ucwords(str_replace('_', ' ', 'akses_daftar_titik_flow'))],
            ['id' => 'akses_tambah_titik_flow', 'name' => ucwords(str_replace('_', ' ', 'akses_tambah_titik_flow'))],
            ['id' => 'akses_edit_titik_flow', 'name' => ucwords(str_replace('_', ' ', 'akses_edit_titik_flow'))],
            ['id' => 'akses_hapus_titik_flow', 'name' => ucwords(str_replace('_', ' ', 'akses_hapus_titik_flow'))],
            ['id' => 'akses_daftar_titik_monitoring_perjam', 'name' => ucwords(str_replace('_', ' ', 'akses_daftar_titik_monitoring_perjam'))],
            ['id' => 'akses_tambah_titik_monitoring_perjam', 'name' => ucwords(str_replace('_', ' ', 'akses_tambah_titik_monitoring_perjam'))],
            ['id' => 'akses_edit_titik_monitoring_perjam', 'name' => ucwords(str_replace('_', ' ', 'akses_edit_titik_monitoring_perjam'))],
            ['id' => 'akses_hapus_titik_monitoring_perjam', 'name' => ucwords(str_replace('_', ' ', 'akses_hapus_titik_monitoring_perjam'))],
            ['id' => 'akses_daftar_titik_monitoring_pershift', 'name' => ucwords(str_replace('_', ' ', 'akses_daftar_titik_monitoring_pershift'))],
            ['id' => 'akses_tambah_titik_monitoring_pershift', 'name' => ucwords(str_replace('_', ' ', 'akses_tambah_titik_monitoring_pershift'))],
            ['id' => 'akses_edit_titik_monitoring_pershift', 'name' => ucwords(str_replace('_', ' ', 'akses_edit_titik_monitoring_pershift'))],
            ['id' => 'akses_hapus_titik_monitoring_pershift', 'name' => ucwords(str_replace('_', ' ', 'akses_hapus_titik_monitoring_pershift'))],
            ['id' => 'akses_daftar_titik_taksasi', 'name' => ucwords(str_replace('_', ' ', 'akses_daftar_titik_taksasi'))],
            ['id' => 'akses_tambah_titik_taksasi', 'name' => ucwords(str_replace('_', ' ', 'akses_tambah_titik_taksasi'))],
            ['id' => 'akses_edit_titik_taksasi', 'name' => ucwords(str_replace('_', ' ', 'akses_edit_titik_taksasi'))],
            ['id' => 'akses_hapus_titik_taksasi', 'name' => ucwords(str_replace('_', ' ', 'akses_hapus_titik_taksasi'))],
            ['id' => 'akses_daftar_barang', 'name' => ucwords(str_replace('_', ' ', 'akses_daftar_barang'))],
            ['id' => 'akses_tambah_barang', 'name' => ucwords(str_replace('_', ' ', 'akses_tambah_barang'))],
            ['id' => 'akses_edit_barang', 'name' => ucwords(str_replace('_', ' ', 'akses_edit_barang'))],
            ['id' => 'akses_hapus_barang', 'name' => ucwords(str_replace('_', ' ', 'akses_hapus_barang'))],
            ['id' => 'akses_daftar_wilayah', 'name' => ucwords(str_replace('_', ' ', 'akses_daftar_wilayah'))],
            ['id' => 'akses_tambah_wilayah', 'name' => ucwords(str_replace('_', ' ', 'akses_tambah_wilayah'))],
            ['id' => 'akses_edit_wilayah', 'name' => ucwords(str_replace('_', ' ', 'akses_edit_wilayah'))],
            ['id' => 'akses_hapus_wilayah', 'name' => ucwords(str_replace('_', ' ', 'akses_hapus_wilayah'))],
            ['id' => 'akses_daftar_kotoran_tebu', 'name' => ucwords(str_replace('_', ' ', 'akses_daftar_kotoran_tebu'))],
            ['id' => 'akses_tambah_kotoran_tebu', 'name' => ucwords(str_replace('_', ' ', 'akses_tambah_kotoran_tebu'))],
            ['id' => 'akses_edit_kotoran_tebu', 'name' => ucwords(str_replace('_', ' ', 'akses_edit_kotoran_tebu'))],
            ['id' => 'akses_hapus_kotoran_tebu', 'name' => ucwords(str_replace('_', ' ', 'akses_hapus_kotoran_tebu'))],
            ['id' => 'akses_daftar_varietas_tebu', 'name' => ucwords(str_replace('_', ' ', 'akses_daftar_varietas_tebu'))],
            ['id' => 'akses_tambah_varietas_tebu', 'name' => ucwords(str_replace('_', ' ', 'akses_tambah_varietas_tebu'))],
            ['id' => 'akses_edit_varietas_tebu', 'name' => ucwords(str_replace('_', ' ', 'akses_edit_varietas_tebu'))],
            ['id' => 'akses_hapus_varietas_tebu', 'name' => ucwords(str_replace('_', ' ', 'akses_hapus_varietas_tebu'))],
            ['id' => 'akses_daftar_kawalan_tebu', 'name' => ucwords(str_replace('_', ' ', 'akses_daftar_kawalan_tebu'))],
            ['id' => 'akses_tambah_kawalan_tebu', 'name' => ucwords(str_replace('_', ' ', 'akses_tambah_kawalan_tebu'))],
            ['id' => 'akses_edit_kawalan_tebu', 'name' => ucwords(str_replace('_', ' ', 'akses_edit_kawalan_tebu'))],
            ['id' => 'akses_hapus_kawalan_tebu', 'name' => ucwords(str_replace('_', ' ', 'akses_hapus_kawalan_tebu'))],
            ['id' => 'akses_daftar_faktor', 'name' => ucwords(str_replace('_', ' ', 'akses_daftar_faktor'))],
            ['id' => 'akses_tambah_faktor', 'name' => ucwords(str_replace('_', ' ', 'akses_tambah_faktor'))],
            ['id' => 'akses_edit_faktor', 'name' => ucwords(str_replace('_', ' ', 'akses_edit_faktor'))],
            ['id' => 'akses_hapus_faktor', 'name' => ucwords(str_replace('_', ' ', 'akses_hapus_faktor'))],
            ['id' => 'akses_daftar_barcode', 'name' => ucwords(str_replace('_', ' ', 'akses_daftar_barcode'))],
            ['id' => 'akses_cetak_barcode', 'name' => ucwords(str_replace('_', ' ', 'akses_cetak_barcode'))],
            ['id' => 'akses_edit_timestamp_barcode', 'name' => ucwords(str_replace('_', ' ', 'akses_edit_timestamp_barcode'))],
            ['id' => 'akses_edit_material_barcode', 'name' => ucwords(str_replace('_', ' ', 'akses_edit_material_barcode'))],
            ['id' => 'akses_input_data', 'name' => ucwords(str_replace('_', ' ', 'akses_input_data'))],
            ['id' => 'akses_daftar_analisa', 'name' => ucwords(str_replace('_', ' ', 'akses_daftar_analisa'))],
            ['id' => 'akses_edit_analisa', 'name' => ucwords(str_replace('_', ' ', 'akses_edit_analisa'))],
            ['id' => 'akses_hapus_analisa', 'name' => ucwords(str_replace('_', ' ', 'akses_hapus_analisa'))],
            ['id' => 'akses_daftar_revisi_analisa', 'name' => ucwords(str_replace('_', ' ', 'akses_daftar_revisi_analisa'))],
            ['id' => 'akses_ajukan_revisi_analisa', 'name' => ucwords(str_replace('_', ' ', 'akses_ajukan_revisi_analisa'))],
            ['id' => 'akses_setujui_revisi_analisa', 'name' => ucwords(str_replace('_', ' ', 'akses_setujui_revisi_analisa'))],
            ['id' => 'akses_verifikasi_mandor', 'name' => ucwords(str_replace('_', ' ', 'akses_verifikasi_mandor'))],
            ['id' => 'akses_daftar_analisa_brix_pol', 'name' => ucwords(str_replace('_', ' ', 'akses_daftar_analisa_brix_pol'))],
            ['id' => 'akses_tambah_analisa_brix_pol', 'name' => ucwords(str_replace('_', ' ', 'akses_tambah_analisa_brix_pol'))],
            ['id' => 'akses_daftar_analisa_rendemen', 'name' => ucwords(str_replace('_', ' ', 'akses_daftar_analisa_rendemen'))],
            ['id' => 'akses_tambah_analisa_rendemen', 'name' => ucwords(str_replace('_', ' ', 'akses_tambah_analisa_rendemen'))],
            ['id' => 'akses_daftar_analisa_ampas_metode_panas', 'name' => ucwords(str_replace('_', ' ', 'akses_daftar_analisa_ampas_metode_panas'))],
            ['id' => 'akses_tambah_analisa_ampas_metode_panas', 'name' => ucwords(str_replace('_', ' ', 'akses_tambah_analisa_ampas_metode_panas'))],
            ['id' => 'akses_daftar_analisa_ampas_metode_dingin', 'name' => ucwords(str_replace('_', ' ', 'akses_daftar_analisa_ampas_metode_dingin'))],
            ['id' => 'akses_tambah_analisa_ampas_metode_dingin', 'name' => ucwords(str_replace('_', ' ', 'akses_tambah_analisa_ampas_metode_dingin'))],
            ['id' => 'akses_daftar_analisa_ketel', 'name' => ucwords(str_replace('_', ' ', 'akses_daftar_analisa_ketel'))],
            ['id' => 'akses_tambah_analisa_ketel', 'name' => ucwords(str_replace('_', ' ', 'akses_tambah_analisa_ketel'))],
            ['id' => 'akses_daftar_analisa_cao', 'name' => ucwords(str_replace('_', ' ', 'akses_daftar_analisa_cao'))],
            ['id' => 'akses_tambah_analisa_cao', 'name' => ucwords(str_replace('_', ' ', 'akses_tambah_analisa_cao'))],
            ['id' => 'akses_daftar_analisa_so2', 'name' => ucwords(str_replace('_', ' ', 'akses_daftar_analisa_so2'))],
            ['id' => 'akses_tambah_analisa_so2', 'name' => ucwords(str_replace('_', ' ', 'akses_tambah_analisa_so2'))],
            ['id' => 'akses_daftar_analisa_bjb', 'name' => ucwords(str_replace('_', ' ', 'akses_daftar_analisa_bjb'))],
            ['id' => 'akses_tambah_analisa_bjb', 'name' => ucwords(str_replace('_', ' ', 'akses_tambah_analisa_bjb'))],
            ['id' => 'akses_daftar_analisa_lain', 'name' => ucwords(str_replace('_', ' ', 'akses_daftar_analisa_lain'))],
            ['id' => 'akses_tambah_analisa_lain', 'name' => ucwords(str_replace('_', ' ', 'akses_tambah_analisa_lain'))],
            ['id' => 'akses_daftar_uji_karung', 'name' => ucwords(str_replace('_', ' ', 'akses_daftar_uji_karung'))],
            ['id' => 'akses_tambah_uji_karung', 'name' => ucwords(str_replace('_', ' ', 'akses_tambah_uji_karung'))],
            ['id' => 'akses_edit_uji_karung', 'name' => ucwords(str_replace('_', ' ', 'akses_edit_uji_karung'))],
            ['id' => 'akses_hapus_uji_karung', 'name' => ucwords(str_replace('_', ' ', 'akses_hapus_uji_karung'))],
            ['id' => 'akses_daftar_flow_nm', 'name' => ucwords(str_replace('_', ' ', 'akses_daftar_flow_nm'))],
            ['id' => 'akses_edit_flow_nm', 'name' => ucwords(str_replace('_', ' ', 'akses_edit_flow_nm'))],
            ['id' => 'akses_tambah_flow_nm', 'name' => ucwords(str_replace('_', ' ', 'akses_tambah_flow_nm'))],
            ['id' => 'akses_hapus_flow_nm', 'name' => ucwords(str_replace('_', ' ', 'akses_hapus_flow_nm'))],
            // ['id' => 'akses_daftar_keliling_proses', 'name' => ucwords(str_replace('_', ' ', 'akses_daftar_keliling_proses'))],
            // ['id' => 'akses_tambah_keliling_proses', 'name' => ucwords(str_replace('_', ' ', 'akses_tambah_keliling_proses'))],
            ['id' => 'akses_daftar_imbibisi', 'name' => ucwords(str_replace('_', ' ', 'akses_daftar_imbibisi'))],
            ['id' => 'akses_tambah_imbibisi', 'name' => ucwords(str_replace('_', ' ', 'akses_tambah_imbibisi'))],
            ['id' => 'akses_edit_imbibisi', 'name' => ucwords(str_replace('_', ' ', 'akses_edit_imbibisi'))],
            ['id' => 'akses_hapus_imbibisi', 'name' => ucwords(str_replace('_', ' ', 'akses_hapus_imbibisi'))],
            ['id' => 'akses_daftar_monitoring_perjam', 'name' => ucwords(str_replace('_', ' ', 'akses_daftar_monitoring_perjam'))],
            ['id' => 'akses_tambah_monitoring_perjam', 'name' => ucwords(str_replace('_', ' ', 'akses_tambah_monitoring_perjam'))],
            ['id' => 'akses_edit_monitoring_perjam', 'name' => ucwords(str_replace('_', ' ', 'akses_edit_monitoring_perjam'))],
            ['id' => 'akses_hapus_monitoring_perjam', 'name' => ucwords(str_replace('_', ' ', 'akses_hapus_monitoring_perjam'))],
            ['id' => 'akses_daftar_monitoring_pershift', 'name' => ucwords(str_replace('_', ' ', 'akses_daftar_monitoring_pershift'))],
            ['id' => 'akses_tambah_monitoring_pershift', 'name' => ucwords(str_replace('_', ' ', 'akses_tambah_monitoring_pershift'))],
            ['id' => 'akses_edit_monitoring_pershift', 'name' => ucwords(str_replace('_', ' ', 'akses_edit_monitoring_pershift'))],
            ['id' => 'akses_hapus_monitoring_pershift', 'name' => ucwords(str_replace('_', ' ', 'akses_hapus_monitoring_pershift'))],
            ['id' => 'akses_daftar_taksasi_proses', 'name' => ucwords(str_replace('_', ' ', 'akses_daftar_taksasi_proses'))],
            ['id' => 'akses_tambah_taksasi_proses', 'name' => ucwords(str_replace('_', ' ', 'akses_tambah_taksasi_proses'))],
            ['id' => 'akses_edit_taksasi_proses', 'name' => ucwords(str_replace('_', ' ', 'akses_edit_taksasi_proses'))],
            ['id' => 'akses_hapus_taksasi_proses', 'name' => ucwords(str_replace('_', ' ', 'akses_hapus_taksasi_proses'))],
            ['id' => 'akses_daftar_gula_dikarungi', 'name' => ucwords(str_replace('_', ' ', 'akses_daftar_gula_dikarungi'))],
            ['id' => 'akses_tambah_gula_dikarungi', 'name' => ucwords(str_replace('_', ' ', 'akses_tambah_gula_dikarungi'))],
            ['id' => 'akses_hapus_gula_dikarungi', 'name' => ucwords(str_replace('_', ' ', 'akses_hapus_gula_dikarungi'))],
            ['id' => 'akses_daftar_timbangan_tetes', 'name' => ucwords(str_replace('_', ' ', 'akses_daftar_timbangan_tetes'))],
            ['id' => 'akses_tambah_timbangan_tetes', 'name' => ucwords(str_replace('_', ' ', 'akses_tambah_timbangan_tetes'))],
            ['id' => 'akses_edit_timbangan_tetes', 'name' => ucwords(str_replace('_', ' ', 'akses_edit_timbangan_tetes'))],
            ['id' => 'akses_hapus_timbangan_tetes', 'name' => ucwords(str_replace('_', ' ', 'akses_hapus_timbangan_tetes'))],
            ['id' => 'akses_daftar_transaksi_stok', 'name' => ucwords(str_replace('_', ' ', 'akses_daftar_transaksi_stok'))],
            ['id' => 'akses_tambah_transaksi_stok', 'name' => ucwords(str_replace('_', ' ', 'akses_tambah_transaksi_stok'))],
            ['id' => 'akses_hapus_transaksi_stok', 'name' => ucwords(str_replace('_', ' ', 'akses_hapus_transaksi_stok'))],
            // ['id' => 'akses_daftar_mutasi_stok', 'name' => ucwords(str_replace('_', ' ', 'akses_daftar_mutasi_stok'))],
            ['id' => 'akses_daftar_gelas_core', 'name' => ucwords(str_replace('_', ' ', 'akses_daftar_gelas_core'))],
            ['id' => 'akses_tambah_gelas_core', 'name' => ucwords(str_replace('_', ' ', 'akses_tambah_gelas_core'))],
            ['id' => 'akses_hapus_gelas_core', 'name' => ucwords(str_replace('_', ' ', 'akses_hapus_gelas_core'))],
            ['id' => 'akses_daftar_gelas_ari', 'name' => ucwords(str_replace('_', ' ', 'akses_daftar_gelas_ari'))],
            ['id' => 'akses_tambah_gelas_ari', 'name' => ucwords(str_replace('_', ' ', 'akses_tambah_gelas_ari'))],
            ['id' => 'akses_hapus_gelas_ari', 'name' => ucwords(str_replace('_', ' ', 'akses_hapus_gelas_ari'))],
            ['id' => 'akses_daftar_posbrix', 'name' => ucwords(str_replace('_', ' ', 'akses_daftar_posbrix'))],
            ['id' => 'akses_tambah_posbrix', 'name' => ucwords(str_replace('_', ' ', 'akses_tambah_posbrix'))],
            ['id' => 'akses_edit_posbrix', 'name' => ucwords(str_replace('_', ' ', 'akses_edit_posbrix'))],
            ['id' => 'akses_hapus_posbrix', 'name' => ucwords(str_replace('_', ' ', 'akses_hapus_posbrix'))],
            ['id' => 'akses_daftar_core_sample', 'name' => ucwords(str_replace('_', ' ', 'akses_daftar_core_sample'))],
            ['id' => 'akses_edit_core_sample', 'name' => ucwords(str_replace('_', ' ', 'akses_edit_core_sample'))],
            ['id' => 'akses_hapus_core_sample', 'name' => ucwords(str_replace('_', ' ', 'akses_hapus_core_sample'))],
            ['id' => 'akses_daftar_ari_timbangan', 'name' => ucwords(str_replace('_', ' ', 'akses_daftar_ari_timbangan'))],
            ['id' => 'akses_edit_ari_timbangan', 'name' => ucwords(str_replace('_', ' ', 'akses_edit_ari_timbangan'))],
            ['id' => 'akses_hapus_ari_timbangan', 'name' => ucwords(str_replace('_', ' ', 'akses_hapus_ari_timbangan'))],
            ['id' => 'akses_daftar_penilaian_mbs', 'name' => ucwords(str_replace('_', ' ', 'akses_daftar_penilaian_mbs'))],
            ['id' => 'akses_edit_penilaian_mbs', 'name' => ucwords(str_replace('_', ' ', 'akses_edit_penilaian_mbs'))],
            ['id' => 'akses_hapus_penilaian_mbs', 'name' => ucwords(str_replace('_', ' ', 'akses_hapus_penilaian_mbs'))],
            ['id' => 'akses_hasil_analisa_per_stasiun', 'name' => ucwords(str_replace('_', ' ', 'akses_hasil_analisa_per_stasiun'))],
            ['id' => 'akses_hasil_analisa_per_material', 'name' => ucwords(str_replace('_', ' ', 'akses_hasil_analisa_per_material'))],
            ['id' => 'akses_laporan', 'name' => ucwords(str_replace('_', ' ', 'akses_laporan'))],
            ['id' => 'akses_laporan_analisa', 'name' => ucwords(str_replace('_', ' ', 'akses_laporan_analisa'))],
            ['id' => 'akses_laporan_proses', 'name' => ucwords(str_replace('_', ' ', 'akses_laporan_proses'))],
            ['id' => 'akses_laporan_posbrix', 'name' => ucwords(str_replace('_', ' ', 'akses_laporan_posbrix'))],
            ['id' => 'akses_laporan_core_sample', 'name' => ucwords(str_replace('_', ' ', 'akses_laporan_core_sample'))],
            ['id' => 'akses_laporan_ari_timbangan', 'name' => ucwords(str_replace('_', ' ', 'akses_laporan_ari_timbangan'))],
            ['id' => 'akses_laporan_penilaian_mbs', 'name' => ucwords(str_replace('_', ' ', 'akses_laporan_penilaian_mbs'))],
            ['id' => 'akses_coa_tetes', 'name' => ucwords(str_replace('_', ' ', 'akses_coa_tetes'))],
            ['id' => 'akses_coa_kapur', 'name' => ucwords(str_replace('_', ' ', 'akses_coa_kapur'))],
            ['id' => 'akses_laporan_uji_karung', 'name' => ucwords(str_replace('_', ' ', 'akses_laporan_uji_karung'))],
            ['id' => 'akses_laporan_mutasi_barang', 'name' => ucwords(str_replace('_', ' ', 'akses_laporan_mutasi_barang'))],
        ];
    }
}
